base_url = "https://memoryall0c.github.io"
compile_sass = true
# title = "after-dark theme"
# description = "A robust, elegant dark theme"
generate_feeds = true

[markdown]
highlight_code = true
highlight_theme = "charcoal"

[extra]
author = "mall0c"
after_dark_menu = [{ url = "$BASE_URL", name = "Home" }]
google_analytics = "G-45JQH16K2R"

[extra.telegram_channel]
created_at = "2024-01-13"
id = "mall0c"
logo = "logo.jpg"
